### PR TITLE
Added download counts

### PR DESCRIPTION
**Pull request by IgorTatarnikov**
Adds a column for total downloads and weekly downloads.

The data for daily and monthly downloads is also saved each time the backend runs.

Need to put the PEPY_API_KEY secret into the `.env` file to test locally.

### CODE REVIEW

**Review by adamltyson — APPROVED** [review]
Looks good (not that I know any typescript). Can you fix the conflicts before merging?

**Comment by IgorTatarnikov** [comment]
Testing locally and then I'll merge.

We should set up a daily action to run the backend and deploy the site, to make sure it stays up to date.

**Comment by adamltyson** [comment]
We should be able to add a cron job to the existing workflow right?

**Comment by IgorTatarnikov** [comment]
I think so!

**Pull request merged**
